#!/bin/sh
#
### BEGIN INIT INFO
# Provides: weston
# Required-Start: $local_fs $remote_fs
# Required-Stop: $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

WS_CALUDEV_FILE=/etc/udev/rules.d/ws-calib.rules

if test -e /etc/default/weston ; then
        . /etc/default/weston
fi

killproc() {
        pid=`/bin/pidof $1`
        [ "$pid" != "" ] && kill $pid
}

read CMDLINE < /proc/cmdline
for x in $CMDLINE; do
        case $x in
        weston=false)
		echo "Weston disabled"
		exit 0;
                ;;
        esac
done

case "$1" in
  start)
        . /etc/profile

        # This is all a nasty hack
        if test -z "$XDG_RUNTIME_DIR"; then
                export XDG_RUNTIME_DIR=/run/user/root
                mkdir --parents $XDG_RUNTIME_DIR
                chmod 0700 $XDG_RUNTIME_DIR
        fi

        # Check if we need to calibrate the touchscreen
        if [ -e /dev/input/touchscreen0 -a ! -f "$WS_CALUDEV_FILE" ]; then
                openvt -s weston -- $OPTARGS

                sleep 2
                CAL_VALUES=`weston-calibrator|cut -c21-`
                echo 'SUBSYSTEM=="input", ENV{WL_CALIBRATION}="'$CAL_VALUES'"' > $WS_CALUDEV_FILE

                # Reload and re-run udev rules and restart weston
                udevadm control --reload
                udevadm trigger
                killproc weston
                sleep 2
        fi

        openvt -s weston -- $OPTARGS
  ;;

  stop)
        echo "Stopping Weston"
        killproc weston
  ;;

  restart)
	$0 stop
        sleep 1
        $0 start
  ;;

  *)
        echo "usage: $0 { start | stop | restart }"
  ;;
esac

exit 0
