#!/bin/sh
#
### BEGIN INIT INFO
# Provides: weston
# Required-Start: $local_fs $remote_fs
# Required-Stop: $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

if test -e /etc/default/weston ; then
        . /etc/default/weston
fi

killproc() {
        pid=`/bin/pidof $1`
        [ "$pid" != "" ] && kill $pid
}

read CMDLINE < /proc/cmdline
for x in $CMDLINE; do
        case $x in
        weston=false)
		echo "Weston disabled"
		exit 0;
                ;;
        esac
done

case "$1" in
  start)
        . /etc/profile

	export XDG_CONFIG_HOME=/etc/
	export WS_CALUDEV_FILE=/etc/udev/rules.d/ws-calibrate.rules

	export XDG_RUNTIME_DIR=/run/user/root
	mkdir --parents $XDG_RUNTIME_DIR
	chmod 0700 $XDG_RUNTIME_DIR

	[ ! -d /dev/dri ] && OPTARGS="$OPTARGS --backend=fbdev-backend.so"

        openvt -s weston -- $OPTARGS

	# If there's no touchscreen device available, done
	if [ ! -e /dev/input/touchscreen0 ] ; then
		exit 0
	fi

	# If it was already calibrated, done
	if [ -f "$WS_CALUDEV_FILE" ] ; then
		exit 0
	fi

	sleep 1

	CAL_VALUES=`weston-calibrator|cut -c21-`
	echo 'SUBSYSTEM=="input", ENV{WL_CALIBRATION}="'$CAL_VALUES'"' > $WS_CALUDEV_FILE
	echo "."

	# Reload and re-run udev rules and restart weston
	udevadm control --reload
	udevadm trigger
	killproc weston
	sleep 2
	openvt -s weston -- $OPTARGS
  ;;

  stop)
        echo "Stopping Weston"
        killproc weston
  ;;

  restart)
	$0 stop
        sleep 1
        $0 start
  ;;

  *)
        echo "usage: $0 { start | stop | restart }"
  ;;
esac

exit 0
